version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
